In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
import scipy.stats as stats

In [2]:
initial_dataset = pd.read_csv("data/global_power_plant_database.csv")
initial_dataset.head()

/var/folders/hq/wqwzmqh53mx_hqlw2tl75b9c0000gn/T/ipykernel_99415/182943708.py:1: DtypeWarning: Columns (0: other_fuel3) have mixed types. Specify dtype option on import or set low_memory=False.
  initial_dataset = pd.read_csv("data/global_power_plant_database.csv")

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.0,32.322,65.1190,Hydro,NaN,NaN,...,123.77,162.90,97.39,137.76,119.50,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
1,AFG,Afghanistan,Kandahar DOG,WKS0070144,10.0,31.670,65.7950,Solar,NaN,NaN,...,18.43,17.48,18.25,17.70,18.29,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
2,AFG,Afghanistan,Kandahar JOL,WKS0071196,10.0,31.623,65.7920,Solar,NaN,NaN,...,18.64,17.58,19.10,17.62,18.72,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.0,34.556,69.4787,Hydro,NaN,NaN,...,225.06,203.55,146.90,230.18,174.91,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.0,34.641,69.7170,Hydro,NaN,NaN,...,406.16,357.22,270.99,395.38,350.80,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1

In [3]:
initial_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 34936 entries, 0 to 34935
Data columns (total 36 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country                         34936 non-null  str
 1   country_long                    34936 non-null  str
 2   name                            34936 non-null  str
 3   gppd_idnr                       34936 non-null  str
 4   capacity_mw                     34936 non-null  float64
 5   latitude                        34936 non-null  float64
 6   longitude                       34936 non-null  float64
 7   primary_fuel                    34936 non-null  str
 8   other_fuel1                     1944 non-null   str
 9   other_fuel2                     276 non-null    str
 10  other_fuel3                     92 non-null     str
 11  commissioning_year              17447 non-null  float64
 12  owner                           20868 non-null  str
 13  source                          34921 non-null  str
 14  url                             34918 non-null  str
 15  geolocation_source              34517 non-null  str
 16  wepp_id                         16234 non-null  str
 17  year_of_capacity_data           14887 non-null  float64
 18  generation_gwh_2013             6417 non-null   float64
 19  generation_gwh_2014             7226 non-null   float64
 20  generation_gwh_2015             8203 non-null   float64
 21  generation_gwh_2016             9144 non-null   float64
 22  generation_gwh_2017             9500 non-null   float64
 23  generation_gwh_2018             9637 non-null   float64
 24  generation_gwh_2019             9659 non-null   float64
 25  generation_data_source          11400 non-null  str
 26  estimated_generation_gwh_2013   16120 non-null  float64
 27  estimated_generation_gwh_2014   16503 non-null  float64
 28  estimated_generation_gwh_2015   17050 non-null  float64
 29  estimated_generation_gwh_2016   17570 non-null  float64
 30  estimated_generation_gwh_2017   33138 non-null  float64
 31  estimated_generation_note_2013  34936 non-null  str
 32  estimated_generation_note_2014  34936 non-null  str
 33  estimated_generation_note_2015  34936 non-null  str
 34  estimated_generation_note_2016  34936 non-null  str
 35  estimated_generation_note_2017  34936 non-null  str
dtypes: float64(17), str(19)
memory usage: 9.6 MB

In [19]:
initial_dataset.describe()

,capacity_mw,latitude,longitude,commissioning_year,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,generation_gwh_2018,generation_gwh_2019,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017
count,34936.000000,34936.000000,34936.000000,17447.000000,14887.000000,6417.000000,7226.000000,8203.000000,9144.000000,9500.000000,9637.000000,9659.000000,16120.000000,16503.000000,17050.000000,17570.000000,33138.000000
mean,163.355148,32.816637,-6.972803,1997.414823,2018.218849,592.696107,656.863891,762.368840,693.149763,661.834161,517.320785,423.922436,239.112221,242.431122,235.866067,235.695265,716.443378
std,489.636072,22.638603,78.405850,23.397835,1.606428,2174.833482,2231.464288,2533.459828,2404.516759,2369.296957,1975.302686,1698.506485,1191.258172,1285.798297,1267.005223,1259.559841,2484.361200
min,1.000000,-77.847000,-179.977700,1896.000000,2000.000000,-947.600000,-989.619000,-864.428000,-768.620000,-934.944000,-982.622000,-780.339000,1.120000,0.870000,0.440000,0.300000,0.000000
25%,4.900000,29.256475,-77.641550,1988.000000,2017.000000,1.947000,2.260000,2.664500,2.729000,2.467000,2.242000,2.751500,8.620000,8.680000,8.380000,8.322500,8.180000
50%,16.745000,39.727750,-2.127100,2007.000000,2019.000000,23.426000,23.608500,26.142000,22.462389,17.876500,12.530000,11.530000,27.620000,28.250000,26.830000,27.555000,37.590000
75%,75.344250,46.263125,49.502675,2014.000000,2019.000000,199.706000,226.322250,285.862583,249.866750,214.505150,151.117000,122.781498,106.805000,106.980000,103.120000,107.237500,229.565000
max,22500.000000,71.292000,179.388700,2020.000000,2019.000000,50834.000000,32320.917000,37433.607000,32377.477000,36448.643000,35136.000000,31920.368000,48675.060000,58470.770000,57113.350000,60859.730000,82810.770000

In [5]:
df = initial_dataset.copy()

In [6]:
# Checking for duplicates and dropping them
count_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {count_duplicates}")
df = df.drop_duplicates()
print(f"Number of duplicate rows after dropping: {df.duplicated().sum()}")

Number of duplicate rows: 0
Number of duplicate rows after dropping: 0

In [7]:
count_missing_values = df.isnull().sum()
print(f"Number of missing values in each column:\n{count_missing_values}")

Number of missing values in each column:
country                               0
country_long                          0
name                                  0
gppd_idnr                             0
capacity_mw                           0
latitude                              0
longitude                             0
primary_fuel                          0
other_fuel1                       32992
other_fuel2                       34660
other_fuel3                       34844
commissioning_year                17489
owner                             14068
source                               15
url                                  18
geolocation_source                  419
wepp_id                           18702
year_of_capacity_data             20049
generation_gwh_2013               28519
generation_gwh_2014               27710
generation_gwh_2015               26733
generation_gwh_2016               25792
generation_gwh_2017               25436
generation_gwh_2018               25299
generation_gwh_2019               25277
generation_data_source            23536
estimated_generation_gwh_2013     18816
estimated_generation_gwh_2014     18433
estimated_generation_gwh_2015     17886
estimated_generation_gwh_2016     17366
estimated_generation_gwh_2017      1798
estimated_generation_note_2013        0
estimated_generation_note_2014        0
estimated_generation_note_2015        0
estimated_generation_note_2016        0
estimated_generation_note_2017        0
dtype: int64

In [8]:
# Handling missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing %': missing_percentage
})

missing_df.sort_values('Missing %', ascending=False)

                                Missing Count  Missing %
other_fuel3                             34844  99.736661
other_fuel2                             34660  99.209984
other_fuel1                             32992  94.435539
generation_gwh_2013                     28519  81.632127
generation_gwh_2014                     27710  79.316464
generation_gwh_2015                     26733  76.519922
generation_gwh_2016                     25792  73.826425
generation_gwh_2017                     25436  72.807419
generation_gwh_2018                     25299  72.415274
generation_gwh_2019                     25277  72.352301
generation_data_source                  23536  67.368903
year_of_capacity_data                   20049  57.387795
estimated_generation_gwh_2013           18816  53.858484
wepp_id                                 18702  53.532173
estimated_generation_gwh_2014           18433  52.762194
estimated_generation_gwh_2015           17886  51.196474
commissioning_year                      17489  50.060110
estimated_generation_gwh_2016           17366  49.708038
owner                                   14068  40.267918
estimated_generation_gwh_2017            1798   5.146554
geolocation_source                        419   1.199336
url                                        18   0.051523
source                                     15   0.042936
country                                     0   0.000000
gppd_idnr                                   0   0.000000
name                                        0   0.000000
country_long                                0   0.000000
capacity_mw                                 0   0.000000
primary_fuel                                0   0.000000
longitude                                   0   0.000000
latitude                                    0   0.000000
estimated_generation_note_2013              0   0.000000
estimated_generation_note_2014              0   0.000000
estimated_generation_note_2015              0   0.000000
estimated_generation_note_2016              0   0.000000
estimated_generation_note_2017              0   0.000000

In [9]:
missing_df_2 = (df.isnull().mean() * 100)\
    .sort_values(ascending=False)\
    .to_frame('Missing %')
    
missing_df_2

                                Missing %
other_fuel3                     99.736661
other_fuel2                     99.209984
other_fuel1                     94.435539
generation_gwh_2013             81.632127
generation_gwh_2014             79.316464
generation_gwh_2015             76.519922
generation_gwh_2016             73.826425
generation_gwh_2017             72.807419
generation_gwh_2018             72.415274
generation_gwh_2019             72.352301
generation_data_source          67.368903
year_of_capacity_data           57.387795
estimated_generation_gwh_2013   53.858484
wepp_id                         53.532173
estimated_generation_gwh_2014   52.762194
estimated_generation_gwh_2015   51.196474
commissioning_year              50.060110
estimated_generation_gwh_2016   49.708038
owner                           40.267918
estimated_generation_gwh_2017    5.146554
geolocation_source               1.199336
url                              0.051523
source                           0.042936
country                          0.000000
gppd_idnr                        0.000000
name                             0.000000
country_long                     0.000000
capacity_mw                      0.000000
primary_fuel                     0.000000
longitude                        0.000000
latitude                         0.000000
estimated_generation_note_2013   0.000000
estimated_generation_note_2014   0.000000
estimated_generation_note_2015   0.000000
estimated_generation_note_2016   0.000000
estimated_generation_note_2017   0.000000

In [10]:
# 1. Colonnes > 50%
drop_cols = missing_percentage[missing_percentage > 50].index

df = df.drop(columns=drop_cols)

# 2. Colonnes numériques
num_cols = df.select_dtypes(include='number').columns

# 3. Colonnes catégorielles
cat_cols = df.select_dtypes(include=['object', 'str']).columns

In [11]:
num_imputer = SimpleImputer(strategy='median')
cat_imputer = SimpleImputer(strategy='most_frequent')

df[num_cols] = num_imputer.fit_transform(df[num_cols])
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

In [12]:
print("Checking for Missing Values:\n")
print(df.isnull().sum())

Checking for Missing Values:

country                           0
country_long                      0
name                              0
gppd_idnr                         0
capacity_mw                       0
latitude                          0
longitude                         0
primary_fuel                      0
owner                             0
source                            0
url                               0
geolocation_source                0
estimated_generation_gwh_2016     0
estimated_generation_gwh_2017     0
estimated_generation_note_2013    0
estimated_generation_note_2014    0
estimated_generation_note_2015    0
estimated_generation_note_2016    0
estimated_generation_note_2017    0
dtype: int64

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34936 entries, 0 to 34935
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country                         34936 non-null  str
 1   country_long                    34936 non-null  str
 2   name                            34936 non-null  str
 3   gppd_idnr                       34936 non-null  str
 4   capacity_mw                     34936 non-null  float64
 5   latitude                        34936 non-null  float64
 6   longitude                       34936 non-null  float64
 7   primary_fuel                    34936 non-null  str
 8   owner                           34936 non-null  str
 9   source                          34936 non-null  str
 10  url                             34936 non-null  str
 11  geolocation_source              34936 non-null  str
 12  estimated_generation_gwh_2016   34936 non-null  float64
 13  estimated_generation_gwh_2017   34936 non-null  float64
 14  estimated_generation_note_2013  34936 non-null  str
 15  estimated_generation_note_2014  34936 non-null  str
 16  estimated_generation_note_2015  34936 non-null  str
 17  estimated_generation_note_2016  34936 non-null  str
 18  estimated_generation_note_2017  34936 non-null  str
dtypes: float64(5), str(14)
memory usage: 5.1 MB

In [16]:
# Safely convert relevant columns to numerical types if necessary.
# If a column named 'numeric_column' exists, convert it.
# Otherwise, fall back to converting the numeric columns identified earlier (num_cols).

if 'numeric_column' in df.columns:
	cols_to_convert = ['numeric_column']
else:
	# num_cols is defined in an earlier cell and contains the numeric columns we want to ensure are numeric
	cols_to_convert = list(num_cols)

# Record missing counts before conversion
before_na = df[cols_to_convert].isna().sum()

# Convert columns to numeric (coerce errors to NaN)
for col in cols_to_convert:
	df[col] = pd.to_numeric(df[col], errors='coerce')

# Record missing counts after conversion
after_na = df[cols_to_convert].isna().sum()

print("Missing values before conversion:\n", before_na)
print("Missing values after conversion:\n", after_na)
print("Newly introduced missing values (after - before):\n", (after_na - before_na))

Missing values before conversion:
 capacity_mw                      0
latitude                         0
longitude                        0
estimated_generation_gwh_2016    0
estimated_generation_gwh_2017    0
dtype: int64
Missing values after conversion:
 capacity_mw                      0
latitude                         0
longitude                        0
estimated_generation_gwh_2016    0
estimated_generation_gwh_2017    0
dtype: int64
Newly introduced missing values (after - before):
 capacity_mw                      0
latitude                         0
longitude                        0
estimated_generation_gwh_2016    0
estimated_generation_gwh_2017    0
dtype: int64

In [17]:
# Record missing counts before conversion
before_na = df[cols_to_convert].isna().sum()

# Use numpy.vectorize to safely coerce values to float (non-convertible -> np.nan)
def _safe_float(x):
    try:
        return float(x)
    except Exception:
        return np.nan

_vec = np.vectorize(_safe_float)

for col in cols_to_convert:
    df[col] = _vec(df[col].values)

# Record missing counts after conversion
after_na = df[cols_to_convert].isna().sum()

print("Missing values before conversion:\n", before_na)
print("Missing values after conversion:\n", after_na)
print("Newly introduced missing values (after - before):\n", (after_na - before_na))

Missing values before conversion:
 capacity_mw                      0
latitude                         0
longitude                        0
estimated_generation_gwh_2016    0
estimated_generation_gwh_2017    0
dtype: int64
Missing values after conversion:
 capacity_mw                      0
latitude                         0
longitude                        0
estimated_generation_gwh_2016    0
estimated_generation_gwh_2017    0
dtype: int64
Newly introduced missing values (after - before):
 capacity_mw                      0
latitude                         0
longitude                        0
estimated_generation_gwh_2016    0
estimated_generation_gwh_2017    0
dtype: int64

In [22]:
df_cleaned = df.copy()

In [23]:
df_cleaned.describe()

,capacity_mw,latitude,longitude,estimated_generation_gwh_2016,estimated_generation_gwh_2017
count,34936.000000,34936.000000,34936.000000,34936.000000,34936.000000
mean,163.355148,32.816637,-6.972803,132.232824,681.505825
std,489.636072,22.638603,78.405850,899.269378,2424.229996
min,1.000000,-77.847000,-179.977700,0.300000,0.000000
25%,4.900000,29.256475,-77.641550,27.067500,8.960000
50%,16.745000,39.727750,-2.127100,27.555000,37.590000
75%,75.344250,46.263125,49.502675,28.040000,195.640000
max,22500.000000,71.292000,179.388700,60859.730000,82810.770000

In [27]:
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 34936 entries, 0 to 34935
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country                         34936 non-null  str
 1   country_long                    34936 non-null  str
 2   name                            34936 non-null  str
 3   gppd_idnr                       34936 non-null  str
 4   capacity_mw                     34936 non-null  float64
 5   latitude                        34936 non-null  float64
 6   longitude                       34936 non-null  float64
 7   primary_fuel                    34936 non-null  str
 8   owner                           34936 non-null  str
 9   source                          34936 non-null  str
 10  url                             34936 non-null  str
 11  geolocation_source              34936 non-null  str
 12  estimated_generation_gwh_2016   34936 non-null  float64
 13  estimated_generation_gwh_2017   34936 non-null  float64
 14  estimated_generation_note_2013  34936 non-null  str
 15  estimated_generation_note_2014  34936 non-null  str
 16  estimated_generation_note_2015  34936 non-null  str
 17  estimated_generation_note_2016  34936 non-null  str
 18  estimated_generation_note_2017  34936 non-null  str
dtypes: float64(5), str(14)
memory usage: 5.1 MB

In [25]:
# Exploring the distribution of power plants by country
country_counts = df_cleaned['country_long'].value_counts()
print(country_counts.head(10))

country_long
United States of America    9833
China                       4235
United Kingdom              2751
Brazil                      2360
France                      2155
India                       1589
Germany                     1309
Canada                      1159
Spain                        829
Russia                       545
Name: count, dtype: int64

In [29]:
primary_fuel_counts = df_cleaned['primary_fuel'].value_counts()
print(primary_fuel_counts.head(20))

primary_fuel
Solar             10665
Hydro              7156
Wind               5344
Gas                3998
Coal               2330
Oil                2320
Biomass            1430
Waste              1068
Nuclear             195
Geothermal          189
Storage             135
Other                43
Cogeneration         41
Petcoke              12
Wave and Tidal       10
Name: count, dtype: int64

In [33]:
# Statistical Analysis:
# Perform a statistical analysis of power output by fuel type using NumPy’s statistical functions.
# Use hypothesis testing to determine if the mean power output differs significantly between different fuel types.


# Choose a numeric column that represents power output. Prefer capacity_mw, fallback to estimated_generation_gwh_2017
if 'capacity_mw' in df_cleaned.columns:
	value_col = 'capacity_mw'
elif 'estimated_generation_gwh_2017' in df_cleaned.columns:
	value_col = 'estimated_generation_gwh_2017'
else:
	raise KeyError("No suitable numeric column found for power output analysis (expected 'capacity_mw' or 'estimated_generation_gwh_2017').")

# Group the data by primary fuel type and calculate the mean power output for each group
mean_power_by_fuel = df_cleaned.groupby('primary_fuel')[value_col].mean()
print(f"Mean {value_col} by fuel:\n", mean_power_by_fuel)

# Build groups of numeric arrays for ANOVA (drop NaNs and require at least 2 observations per group)
groups = [
	group[value_col].dropna().values
	for _, group in df_cleaned.groupby('primary_fuel')
	if group[value_col].dropna().size >= 2
]

if len(groups) < 2:
	print("Not enough groups with numeric data to perform ANOVA.")
else:
	# Perform a one-way ANOVA test
	f_stat, p_value = stats.f_oneway(*groups)
	print("\nANOVA F-statistic:", f_stat)
	print("ANOVA p-value:", p_value)

Mean capacity_mw by fuel:
 primary_fuel
Biomass             23.972938
Coal               843.579828
Cogeneration        98.731707
Gas                373.449375
Geothermal          67.130952
Hydro              147.171551
Nuclear           2091.855179
Oil                112.878754
Other               84.020000
Petcoke            202.048125
Solar               17.657039
Storage             12.683704
Waste               13.809657
Wave and Tidal      55.220000
Wind                49.224126
Name: capacity_mw, dtype: float64

ANOVA F-statistic: 967.4600353089313
ANOVA p-value: 0.0

In [35]:
# Time Series Analysis:

# If the dataset includes time-related data (like year of establishment), use NumPy to analyze trends over time.
# Explore how the mix of fuel types for power generation has evolved over the years.

# Choose the best available year column and analyze trends by count and capacity
candidate_year_cols = ['year_of_establishment', 'commissioning_year', 'year_of_capacity_data']
available = [c for c in candidate_year_cols if c in df_cleaned.columns]

if not available:
    print("No suitable year column found. Cannot perform time series analysis.")
else:
    # pick column with the most non-null values
    year_col = max(available, key=lambda c: df_cleaned[c].notna().sum())
    non_null_count = df_cleaned[year_col].notna().sum()
    if non_null_count == 0:
        print(f"Year column {year_col!r} has no non-null values. Cannot perform time series analysis.")
    else:
        # Coerce to numeric years
        df_cleaned[year_col] = pd.to_numeric(df_cleaned[year_col], errors='coerce').astype('Int64')

        # Drop rows missing year or primary_fuel
        tmp = df_cleaned.dropna(subset=[year_col, 'primary_fuel'])

        # Count of plants per year and fuel
        fuel_trends_count = tmp.groupby([year_col, 'primary_fuel']).size().unstack(fill_value=0).sort_index()

        # Sum of capacity (MW) per year and fuel
        if 'capacity_mw' in tmp.columns:
            fuel_trends_capacity = tmp.groupby([year_col, 'primary_fuel'])['capacity_mw'].sum().unstack(fill_value=0).sort_index()
        else:
            fuel_trends_capacity = None

        print(f"Using year column: {year_col!r} (non-null: {non_null_count})\n")
        print("Plant counts by year and fuel (first 10 years):")
        print(fuel_trends_count.head(10))
        if fuel_trends_capacity is not None:
            print("\nTotal capacity (MW) by year and fuel (first 10 years):")
            print(fuel_trends_capacity.head(10))

No suitable year column found. Cannot perform time series analysis.

In [ ]:
# Advanced Visualization:

# Create visualizations using Matplotlib and Seaborn to illustrate your findings.
# Consider plotting the geographical distribution of power plants using latitude and longitude data, if available.